# Generated by Django 2.1.2 on 2018-12-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20181214_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='myfield',
        ),
        migrations.AddField(
            model_name='hobby',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
